services:
  app:
    build: prisma
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    volumes:
      - ../prisma/:/prisma:ro
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - psql-data:/tmp/dev/pgsql/data
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pga-data:/tmp/dev/pga/data
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    volumes:
      - mq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  psql-data:
  pga-data:
  mq-data: